- name: "Product 1"
  image: "/assets/images/product1.jpg"
  price: "$19.99"
  link: "https://example.com/product1"

- name: "Product 2"
  image: "/assets/images/product2.jpg"
  price: "$29.99"
  link: "https://example.com/product2"

- name: "Product 3"
  image: "/assets/images/product3.jpg"
  price: "$39.99"
  link: "https://example.com/product3"

- name: "Product 4"
  image: "/assets/images/product4.jpg"
  price: "$49.99"
  link: "https://example.com/product4"

- name: "Product 5"
  image: "/assets/images/product5.jpg"
  price: "$59.99"
  link: "https://example.com/product5"

- name: "Product 6"
  image: "/assets/images/product6.jpg"
  price: "$69.99"
  link: "https://example.com/product6"

- name: "Product 7"
  image: "/assets/images/product7.jpg"
  price: "$79.99"
  link: "https://example.com/product7"

- name: "Product 8"
  image: "/assets/images/product8.jpg"
  price: "$89.99"
  link: "https://example.com/product8"

- name: "Product 9"
  image: "/assets/images/product9.jpg"
  price: "$99.99"
  link: "https://example.com/product9"

- name: "Product 9"
  image: "/assets/images/product9.jpg"
  price: "$99.99"
  link: "https://example.com/product9"
  
- name: "Product 9"
  image: "/assets/images/product9.jpg"
  price: "$99.99"
  link: "https://example.com/product9"
- name: "Product 9"
  image: "/assets/images/product9.jpg"
  price: "$99.99"
  link: "https://example.com/product9"
  
- name: "Product 9"
  image: "/assets/images/product9.jpg"
  price: "$99.99"
  link: "https://example.com/product9"
# Continue adding products as needed...

